# Generated by Django 2.2.14 on 2021-02-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_app', '0002_auto_20210205_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='recruiter',
        ),
        migrations.AddField(
            model_name='candidate',
            name='recruiter',
            field=models.ManyToManyField(to='orm_app.Recruiter'),
        ),
    ]
