# Generated by Django 2.2.14 on 2021-02-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_app', '0003_auto_20210205_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='number',
            field=models.IntegerField(default=876543),
            preserve_default=False,
        ),
    ]
