# Generated by Django 2.2.14 on 2021-02-12 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orm_app', '0004_recruiter_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='static/product_image')),
                ('price', models.IntegerField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('contact_number', models.IntegerField()),
                ('image', models.ImageField(upload_to='static/profile_image')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
        migrations.DeleteModel(
            name='Recruiter',
        ),
        migrations.AddField(
            model_name='post_ad',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orm_app.Profile'),
        ),
    ]
