# Generated by Django 2.2.14 on 2021-02-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_app', '0005_auto_20210212_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/profile_image'),
        ),
    ]
